name: topix
description: "The Android client of topix."
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: ^3.10.0

dependencies:
  theme_provider: ^0.6.0
  font_awesome_flutter: ^10.12.0
  # animations: ^2.1.1
  provider: ^6.1.5+1
  get_it: ^9.0.5
  # path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
  firebase_core: ^4.2.1
  firebase_remote_config: ^6.1.2
  firebase_analytics: ^12.0.4
  google_sign_in: ^7.2.0
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  # image_picker: ^1.2.1
  video_player: ^2.10.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  # flutter_launcher_icons: ^0.14.4
  import_sorter: ^4.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# yaml configs
import_sorter:
  comments: false
  # dart run import_sorter:main
# flutter_launcher_icons:
#   android: true
#   image_path: 'assets/images/icon.png'
#   min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
