name: Release dev build
on:
  push:
    branches: [ dev ]

permissions:
  contents: write

jobs:
  build_and_release_dev:
    name: Release dev build of topix on GitHub
    if: startsWith(github.event.head_commit.message, '[dev_release]')
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: 3.38.1
          channel: stable
      - run: flutter --version

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0

      - name: Cleaning build
        run: flutter clean

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Write google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: Writing key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Install dependencies
        run: flutter pub get

      - name: Extract version from pubspec.yaml
        run: |
          version_str=$(grep '^version: ' pubspec.yaml | awk '{ print $2 }')
          version_part=$(echo $version_str | cut -d '+' -f 1)
          echo "VERSION=$version_part" >> $GITHUB_ENV

      # dev tag: v1.3.0_dev_2
      - name: Get count of current version dev build
        run: |
          version_count=$(git tag -l "v${{ env.VERSION }}_dev*" | wc -l)
          echo "Found $version_count similar tags"
          version_count=$((version_count + 1))
          echo "VERSION_COUNT=$version_count" >> $GITHUB_ENV

      - name: Create version string for binaries
        run: |
          version_bin=$(echo "${{ env.VERSION }}" | sed 's/\./_/g')
          echo "VERSION_BIN=${version_bin}_dev_${{ env.VERSION_COUNT }}" >> $GITHUB_ENV

      - name: Create new version string for dev build
        run: |
          version_dev="${{ env.VERSION }}_dev_${{ env.VERSION_COUNT }}"
          echo "VERSION=$version_dev" >> $GITHUB_ENV

      - name: Create env
        run: |
          echo "VERSION=${{ env.VERSION }}" > .env

      - name: Build split APKs
        run: flutter build apk --split-per-abi

      - name: Update binary names
        run: |
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/topix_${{ env.VERSION_BIN }}-arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/topix_${{ env.VERSION_BIN }}-armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/topix_${{ env.VERSION_BIN }}-x86_64.apk

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/topix_*.apk"
          bodyFile: "dev_changes.md"
          token: ${{ secrets.API_GITHUB_TOKEN }}
          name: v${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          commit: dev
          generateReleaseNotes: true
          makeLatest: false
          prerelease: true