name: Build and create a release
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build_and_release:
    name: Build and release topix on GitHub
    if: startsWith(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: 3.38.1
          channel: stable
      - run: flutter --version

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cleaning build
        run: flutter clean

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Write google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: Writing key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Install dependencies
        run: flutter pub get

      - name: Extract version from pubspec.yaml
        run: |
          version_str=$(grep '^version: ' pubspec.yaml | awk '{ print $2 }')
          version_part=$(echo $version_str | cut -d '+' -f 1)
          echo "VERSION=$version_part" >> $GITHUB_ENV

      - name: Create version string for binaries
        run: |
          version_bin=$(echo "${{ env.VERSION }}" | sed 's/\./_/g')
          echo "VERSION_BIN=$version_bin" >> $GITHUB_ENV

      - name: Create env
        run: |
          echo "VERSION=${{ env.VERSION }}" > .env

      - name: Build APKs
        run: flutter build apk
      - name: Build split APKs
        run: flutter build apk --split-per-abi

      - name: Update binary names
        run: |
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/topix_${{ env.VERSION_BIN }}-arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/topix_${{ env.VERSION_BIN }}-armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/topix_${{ env.VERSION_BIN }}-x86_64.apk
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/topix_${{ env.VERSION_BIN }}.apk

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/topix_*.apk"
          bodyFile: "release_note.md"
          token: ${{ secrets.API_GITHUB_TOKEN }}
          name: v${{ env.VERSION }}
          tag: v${{ env.VERSION }}
          allowUpdates: true
          commit: main
          generateReleaseNotes: true
          makeLatest: true